### ISSUE TITLE
Your mod has a conflict

### ISSUE THREAD

**Issue by RayzoRayy** [superbas11/MenuMobs#1]
Found out that your mod conflicts with the mod Baubles Stuff. I've created an issue on his form, but figured i'd make one here as well since it seems your mod is conflicting with his. Ill give you the crash report even though it points towards his mod, yours is causing the crash as once i remove your mod, it's fine... what happens is when i launch the pack, it crashes at the main menu with Baubles Stuff mod.

http://pastebin.com/NVbRSzef

**Comment by bschoenmaeckers** [comment]
I'm afraid that I cant fix this. Baubles stuff needs to check if mc.theworld is not null.

**Comment by bschoenmaeckers** [comment]
ZAZPRO/BaublesStuff#3
