### ISSUE TITLE
[1.10.2] Missing Player Pic in menu on exit

### ISSUE THREAD

**Issue by Morpheus1101** [superbas11/MenuMobs#10]
Upon leaving a joined game be it either SP//SMP when goign back to the main menu, there is a Mob displayed, but the display of the player disappears

**Comment by bschoenmaeckers** [comment]
wich mods do you use and can you see an error in the console?

**Comment by Morpheus1101** [comment]
No error in console and mods list im using is @ http://pastebin.com/KWY1etuB

**Comment by bschoenmaeckers** [comment]
Does it happen with every world you leave?

**Comment by Morpheus1101** [comment]
Yes, reguardless of how many worlds i make, its always the same case

**Comment by bschoenmaeckers** [comment]
does this happen in your 1.10 release of your modpack? if so can you give me access to it?

**Comment by Morpheus1101** [comment]
Its in my 1.10.2 Pack im still devaloping and as such isnt uploaded anywhere

**Comment by bschoenmaeckers** [comment]
can you upload it and pm me the link? I really cant find what causes this.

**Comment by Morpheus1101** [comment]
You'll need to use the curse client to import the pack http://www.filedropper.com/arduous2-10

**Comment by bschoenmaeckers** [comment]
Ok tnx!

**Comment by bschoenmaeckers** [comment]
It's caused by schematica, need to look further into it...
bookmark: https://github.com/Lunatrius/Schematica/blob/master/src/main/java/com/github/lunatrius/schematica/handler/client/TickHandler.java#L61-L65
