### ISSUE TITLE
[1.10.2] Menmobs causes EnderStorage to crash on WorldGen

### ISSUE THREAD

**Issue by Morpheus1101** [superbas11/MenuMobs#11]
When creating a SP world, soon as you try and join that world you crash... log @ http://pastebin.com/N7Psu8Em ... refrenced to https://github.com/TheCBProject/EnderStorage/issues/11

**Comment by covers1624** [comment]
As i said in my issue tracker, the only way that can throw an NPE is if a tick event ts fired before the client has the world load event fired.

**Comment by Morpheus1101** [comment]
Issue has been solved

**Comment by Morpheus1101** [comment]
Turns out i was wrong, this hasnt been solved, somehow menumobs had been disabled and i hadnt noticed

**Comment by bschoenmaeckers** [comment]
actually no one released a fix yet XD

**Comment by Morpheus1101** [comment]
I realised after i seen the mod was just disabled for some reason lol, ohh well, _g_
