### ISSUE TITLE
Better Animations Mod Crash

### ISSUE THREAD

**Issue by WenXin20** [superbas11/MenuMobs#12]
If the [Better Animations Mod](https://minecraft.curseforge.com/projects/better-animations-collection-revived-2) is installed, mobs with the animation added either don't show in the menu or crashes the game. 
Forge 2073
[Liteloader is Required ](http://www.liteloader.com)

**Comment by bschoenmaeckers** [comment]
I cant fix this. Please send an issue report to the author of Better Animation Mod.
Known mobs to crash: Slime, Ocelot and Wolf.

**Comment by WenXin20** [comment]
Ok
