### ISSUE TITLE
Husk and Stray don't Show

### ISSUE THREAD

**Issue by WenXin20** [superbas11/MenuMobs#13]
The husk and stray, which are variants of the Zombie and Skeleton, don't show on the main menu.

**Comment by bschoenmaeckers** [comment]
The stray will show up as random variant of the skeleton but the zombie variant isn't yet fully implemented in forge and will probably never be. In mc 1.11 the zombie and skeleton variants will get there own entity.
Sorry but you have to wait for minecraft 1.11.

**Comment by WenXin20** [comment]
OK, thanks

**Comment by bschoenmaeckers** [comment]
Fixed in the mc 1.11 version.
