### ISSUE TITLE
Naming scheme

### ISSUE THREAD

**Issue by C0rn3j** [superbas11/MenuMobs#15]
How about renaming it to [modname]-[MC version]-[mod version].jar just like most of other mods?  

With the way it is set up now it makes it hard to find between a ton of mods without using search or knowing it'd be at the top of the list
http://i.imgur.com/jxSadm2.png

**Comment by bschoenmaeckers** [comment]
I never thought about the naming scheme but that looks a lot better organized. Tnx for the suggestion.
Next release will be named like that.
