### ISSUE TITLE
[1.10.2] crash when opening blacklist UI from mod config

### ISSUE THREAD

**Issue by Cat-McCatface** [superbas11/MenuMobs#16]
was trying to add entities to it (from Inventory Pets and SoggyMustache's Transportation) but it wasn't having any of what I wanted. Doesn't matter if I wipe the config file or whatever.

log: http://pastebin.com/B3jXjK0v
forge: 2076
MenuMobs-1.10.2-1.10

**Comment by bschoenmaeckers** [comment]
Strange looks like a bug in forge. can you give me your full log.

**Comment by Cat-McCatface** [comment]
[fml-client-latest.zip](https://github.com/superbas11/MenuMobs/files/465344/fml-client-latest.zip)

[latest.log.txt](https://github.com/superbas11/MenuMobs/files/465345/latest.log.txt)

Didn't attach logs for mods (giacomosfoundry and futurepack) because of lack of errors (or in the foundry mod case, anything).

I don't get it either :| I'm using vanilla launcher so that shouldn't be doing anything other than the use of current Java VM and 3 gb memory set to MC.

**Comment by bschoenmaeckers** [comment]
Its indeed a bug in forge so I'm going to report this to forge.
I think I found a work around to fix this on my side.

**Comment by Cat-McCatface** [comment]
thanks
