### ISSUE TITLE
Glitched Modded Mobs

### ISSUE THREAD

**Issue by WenXin20** [superbas11/MenuMobs#19]
Golems from the [Extra Golems](https://minecraft.curseforge.com/projects/extra-golems), [Base Metal Golems](https://minecraft.curseforge.com/projects/base-metal-golems-addon), and [Tinkers' Golems](https://minecraft.curseforge.com/projects/tinkers-golems-addon) Mods sometimes show up glitched. They seem to only show the outer skin layer, such as the vines.
For the [Mob Hunter Mod](https://minecraft.curseforge.com/projects/mob-hunter), whenever a big dinosaur is shown, its tail is cut off.
I'm using forge 2121

**Comment by bschoenmaeckers** [comment]
I cannot add support for every mob/creature of every mod. Because of this reason I made a blacklist so you can disable unwanted/broken mobs.
Thank you for your understanding.

**Comment by WenXin20** [comment]
Ok, thanks anyway
