### ISSUE TITLE
Major Leak - 1.10.2 Forge 209

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [superbas11/MenuMobs#20]
When using menu mobs and these mods the title screen spazes out and spams this 

Skipping Entity with id -1

Here is my mod list.
![mobmenu](https://cloud.githubusercontent.com/assets/10351221/21940831/adc75e98-d98b-11e6-9055-747973cc602f.PNG)

**Comment by P3rf3ctXZer0** [comment]
here is the gist 
https://gist.github.com/P3rf3ctXZer0/7f8d5a5cf8d8f1f3369850320ab91e45

**Comment by bschoenmaeckers** [comment]
Thanks for the bug report. Could you enable dubug mode in the menumobs settings please and send me the log of that.

**Comment by P3rf3ctXZer0** [comment]
Yep

**Comment by P3rf3ctXZer0** [comment]
@superbas11 where do I find the debug log?

**Comment by P3rf3ctXZer0** [comment]
![menu mobs](https://cloud.githubusercontent.com/assets/10351221/21945330/4db7ea58-d9a0-11e6-9913-cbf4f44e3edc.PNG)

**Comment by P3rf3ctXZer0** [comment]
Found this while browsing mobs pokecube.core.entity.pokemobs.helper.EntityStatsPokemob.getPokedexEntry(EntityStatsPokemob.java:357)
[15:01:07] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at pokecube.core.interfaces.IPokemob.getPokedexNb(IPokemob.java:782)

**Comment by P3rf3ctXZer0** [comment]
https://github.com/Thutmose/Pokecube/issues/178
