### ISSUE TITLE
NPE w/ Helper Tools Mod

### ISSUE THREAD

**Issue by WenXin20** [superbas11/MenuMobs#22]
**Forge** 2221-1.10.2
[~**Valkyrien Warfare** v0.8.7~](https://minecraft.curseforge.com/projects/valkyrien-warfare)
**Menu Mobs** v1.14.1
I get the following error on the main menu while scrolling through the mobs by clicking the arrow.
It disabled the mobs and the player that was showing. I tried to blacklist the entity, but none shows up in the entity list for blacklisting.

> [09:19:13] [Client thread/ERROR] [menumobs]: Main menu mob rendering encountered a serious error and has been disabled for the remainder of this session.
> [09:19:13] [Client thread/INFO] [STDERR]: [superbas11.menumobs.MainMenuRenderTicker:onTick:470]: net.minecraft.util.ReportedException: Rendering entity in world
> [09:19:13] [Client thread/INFO] [STDERR]: [superbas11.menumobs.MainMenuRenderTicker:onTick:470]: 	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:440)
> [09:19:13] [Client thread/INFO] [STDERR]: [superbas11.menumobs.MainMenuRenderTicker:onTick:470]: 	at ValkyrienWarfareBase.CoreMod.CallRunnerClient.onDoRenderEntity(CallRunnerClient.java:460)
> [09:19:13] [Client thread/INFO] [STDERR]: [superbas11.menumobs.MainMenuRenderTicker:onTick:470]: 	at superbas11.menumobs.client.util.EntityUtils.drawEntityOnScreen(EntityUtils.java:177)
> [09:19:13] [Client thread/INFO] [STDERR]: [superbas11.menumobs.MainMenuRenderTicker:onTick:470]: 	at superbas11.menumobs.MainMenuRenderTicker.onTick(MainMenuRenderTicker.java:447)
> [09:19:13] [Client thread/INFO] [STDERR]: [superbas11.menumobs.MainMenuRenderTicker:onTick:470]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1456_MainMenuRenderTicker_onTick_RenderTickEvent.invoke(.dynamic)
> [09:19:13] [Client thread/INFO] [STDERR]: [superbas11.menumobs.MainMenuRenderTicker:onTick:470]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
> [09:19:13] [Client thread/INFO] [STDERR]: [superbas11.menumobs.MainMenuRenderTicker:onTick:470]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
> [09:19:13] [Client thread/INFO] [STDERR]: [superbas11.menumobs.MainMenuRenderTicker:onTick:470]: 	at net.minecraftforge.fml.common.FMLCommonHandler.onRenderTickStart(FMLCommonHandler.java:350)
> [09:19:13] [Client thread/INFO] [STDERR]: [superbas11.menumobs.MainMenuRenderTicker:onTick:470]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1074)
> [09:19:13] [Client thread/INFO] [STDERR]: [superbas11.menumobs.MainMenuRenderTicker:onTick:470]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
> [09:19:13] [Client thread/INFO] [STDERR]: [superbas11.menumobs.MainMenuRenderTicker:onTick:470]: 	at net.minecraft.client.main.Main.main(SourceFile:124)
> [09:19:13] [Client thread/INFO] [STDERR]: [superbas11.menumobs.MainMenuRenderTicker:onTick:470]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [09:19:13] [Client thread/INFO] [STDERR]: [superbas11.menumobs.MainMenuRenderTicker:onTick:470]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> [09:19:13] [Client thread/INFO] [STDERR]: [superbas11.menumobs.MainMenuRenderTicker:onTick:470]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [09:19:13] [Client thread/INFO] [STDERR]: [superbas11.menumobs.MainMenuRenderTicker:onTick:470]: 	at java.lang.reflect.Method.invoke(Method.java:483)
> [09:19:13] [Client thread/INFO] [STDERR]: [superbas11.menumobs.MainMenuRenderTicker:onTick:470]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> [09:19:13] [Client thread/INFO] [STDERR]: [superbas11.menumobs.MainMenuRenderTicker:onTick:470]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
>

**Comment by bschoenmaeckers** [comment]
Enable debug mode and note the mob ID when it crashes. Go to the option menu and add the mob to the blacklist.

**Comment by bschoenmaeckers** [comment]
Did you find the mob?

**Comment by WenXin20** [comment]
I haven't been able to try debug mode yet, but when I received the NPE, I didn't crash. Will it still show the entity id in the log?
And when looking through the list of entities provided, I don't see an entity for the mod.

**Comment by WenXin20** [comment]
Oops, closing this was an accident

**Comment by bschoenmaeckers** [comment]
The game should not crash when an error occurs and the mob ID will always be in the log when you're in debug mode.

**Comment by WenXin20** [comment]
Ok, thanks.
Though to my knowledge, the mod doesn't add any mobs, but a way to create ships using any block, perhaps it's trying to make an entity thats trying to register in the menu?

**Comment by bschoenmaeckers** [comment]
looking at the mod, it adds a lot of entities for the usage of the airships, cannons and physics.

**Comment by WenXin20** [comment]
Ok, I'll see if I can find the entity causing the problem.

**Comment by bschoenmaeckers** [comment]
There shouldn't  be loading a mob from Valkyrien. I cant reproduce this error either.

**Comment by bschoenmaeckers** [comment]
Can you send me the full error log when it happens again. The last error you send does not tell what the error is.

**Comment by WenXin20** [comment]
Ok, I got it to happen again. When the error occurred, everything on the menu to do with Menu Mobs disappeared, including the blacklist button.
It seems like it was actually caused by the [Helper Tools](https://minecraft.curseforge.com/projects/helper-tools) mod, and the log just happened to mention the Valkyrien Warfare mod too.
Here is the log with that entity:
https://gist.github.com/WenXin20/2db03195efd3c53c9badf6c60121fcfe

**Comment by bschoenmaeckers** [comment]
That's why the "Caused by" section is the most important.

**Comment by WenXin20** [comment]
Yeah, I think when I saw that before I was thinking that was a log for another mod.
Is Entity_Mirage the id of the entity from that mod?

**Comment by bschoenmaeckers** [comment]
I don't know why this happens yet but you can try it.

**Comment by bschoenmaeckers** [comment]
> Is Entity_Mirage the id of the entity from that mod?

I think that's the one!

**Comment by bschoenmaeckers** [comment]
Note for the next time:
Just enable debug mode and the ID should be in the log ;)

[22:59:54] [Client thread/INFO] [menumobs]: Enabling Main Menu Mob render ticker
**[22:59:54] [Client thread/INFO] [menumobs]: helpertools.Mirage**
[22:59:54] [Client thread/ERROR] [menumobs]: Main menu mob rendering encountered a serious error and has been disabled for the remainder of this session.
[22:59:54] [Client thread/INFO] [STDERR]: [superbas11.menumobs.MainMenuRenderTicker:onTick:470]: net.minecraft.util.ReportedException: Rendering entity in world
[22:59:54] [Client thread/INFO] [STDERR]: [superbas11.menumobs.MainMenuRenderTicker:onTick:470]: 	at net.minecraft.client.renderer.entity.RenderManager.doRenderEntity(RenderManager.java:413)

**Comment by WenXin20** [comment]
ok, thanks

**Comment by WenXin20** [comment]
Hmm, after blacklisting it and then reloading the game, all blacklisted mobs still show on the menu.
I opened a separate issue for this.
