### ISSUE TITLE
[Request] Update for Minecreaft 1.12.2

### ISSUE THREAD

**Issue by NekoAmps** [superbas11/MenuMobs#26]
I've been putting off playing MC1.12 for a while as I gave time for mods to update to it. While MenuMobs is just a gimmick mob, it is one of my favorites; I would love to see it in the new menu!

**Comment by bschoenmaeckers** [comment]
I'm a bit busy with uni this weekend but I can try to do something in the spare time.

**Comment by bschoenmaeckers** [comment]
The new version should be on curse in a couple of minutes.
