### ISSUE TITLE
[1.12.2] Menu screen with mobs causes GL Error due to NPE being null

### ISSUE THREAD

**Issue by Morpheus1101** [superbas11/MenuMobs#28]
Error can be viewed at https://gist.github.com/Morpheus1101/491b76e067507b55d98ae404063a0dbc

Seems Menumobs & MoBends mods conflict

**Comment by bschoenmaeckers** [comment]
This mods changes how some things are rendered in a weird way. The game does not crash anymore when rendering but it has some weird side effects (like not rendering the head of the player). Because this mod is in beta, I'm not going to fix the rendering today.
