### ISSUE TITLE
Character is using default skin

### ISSUE THREAD

**Issue by DreadBoy** [superbas11/MenuMobs#4]
Character in main menu is using default Alex skin. My default skin is Steve and I'm also using custom skin. I've attached some screenshots.
![2016-07-02_08 52 40](https://cloud.githubusercontent.com/assets/1308565/16538940/f877f8f0-4032-11e6-951b-0efd5445c4a8.png)
![2016-07-02_08 53 57](https://cloud.githubusercontent.com/assets/1308565/16538941/f87a54c4-4032-11e6-9981-efe17dde4a33.png)
![2016-07-02_08 55 39](https://cloud.githubusercontent.com/assets/1308565/16538942/f8869fae-4032-11e6-9024-4254af31034a.png)
![2016-07-02_08 52 06](https://cloud.githubusercontent.com/assets/1308565/16538943/f890b372-4032-11e6-8299-f567144524d9.png)

**Comment by bschoenmaeckers** [comment]
This issue is fixed in release 1.2 for 1.9.4. Is there a particular reason why you'r still on 1.9?

**Comment by DreadBoy** [comment]
Yes, the server I'm playing on is still on 1.9. Well, if that's fixed in 1.9.4 you can close that issue, I can survive with default skin.

**Comment by bschoenmaeckers** [comment]
OK. Thanks for your issue report.
