### ISSUE TITLE
Crash w/ Config Option

### ISSUE THREAD

**Issue by WenXin20** [superbas11/MenuMobs#6]
Clicking on the players option under the config option for fixed entities crashes the game.
Crash Report: 
http://pastebin.com/8rqgefVf

**Comment by bschoenmaeckers** [comment]
interesting... this shouldn't happen. I think its a compiling bug in forge. I going to look further into this.

**Comment by superbas11** [comment]
fixed in forge 12.18.1.2020.

**Comment by bschoenmaeckers** [comment]
and its still not fixed.....
