### ISSUE TITLE
Chickens Mod

### ISSUE THREAD

**Issue by WenXin20** [superbas11/MenuMobs#8]
I have the Chickens Mod installed, and for some reason it only shows the bone chicken, and the horse and sheep only shows the white one. And would it be possible to have different sizes for slime and Magma slime to show?

**Comment by bschoenmaeckers** [comment]
Does the sheep need all possible color variants or only how they spawn naturally?

**Comment by WenXin20** [comment]
All colors would be neat, but it's up to you.

**Comment by bschoenmaeckers** [comment]
I'm going with all colors!

**Comment by WenXin20** [comment]
Cool, and thanks

**Comment by WenXin20** [comment]
The rabbit also shows only the brown type. Should mobs sometimes show a baby for every one with a baby, such as the pigman, the zombie, and all the passive mobs?

**Comment by bschoenmaeckers** [comment]
baby mobs are the same as the normal one but with a bigger head.

**Comment by bschoenmaeckers** [comment]
added all rabbit types in commit https://github.com/superbas11/MenuMobs/commit/716363f7758a6c2a6487cbb9abddd41543420cf2#diff-7d0252fb584269d322d31057fa1bae75R280
