### ISSUE TITLE
Add a Blacklist for mobs

### ISSUE THREAD

**Issue by WenXin20** [superbas11/MenuMobs#9]
Mainly because [Thuttech](https://minecraft.curseforge.com/projects/thuts-elevators) adds an entity called the elevator, which doesn't show up on the screen when it is selected, and it makes the player become invisible on the main menu.

**Comment by C0rn3j** [comment]
http://i.imgur.com/zUNIfqO.png

Yeah a black list with some predefined mod mobs would do wonders..

**Comment by bschoenmaeckers** [comment]
There is an internal [blacklist](https://github.com/superbas11/MenuMobs/blob/8c4398f4eb12c87315d9776676182c85ed031f8a/src/main/java/superbas11/menumobs/MainMenuRenderTicker.java#L71-L108) for this kind of mobs, but I'm looking for a good way to add mobs to it.

**Comment by C0rn3j** [comment]
How about a(possibly temporary)  small button below the character that can be used to report the offending model to you, and if the button is not pressed it'd report OK to you?

 That'd be a very quick way to determine which ones break stuff and which ones are fine.

**Comment by bschoenmaeckers** [comment]
That sounds like a good option. after pressing the button it will be added to a local blacklist? And an option to edit the list in the config screen.

**Comment by WenXin20** [comment]
Sounds good.

**Comment by C0rn3j** [comment]
> after pressing the button it will be added to a local blacklist?

Added to a local black list and asked if you'd like to upload the mob ID to a database along with a reason why it should be blocked, so it can be blocked by default in a future mod version. Sounds great.

Perhaps add an option in the config list that'd allow people to just list through all the mobs and report all the broken ones. Would populate the list really quick.

**Comment by bschoenmaeckers** [comment]
Does this button look nice?
http://i.imgur.com/m3ni0FR.jpg
and a nice tooltip: http://i.imgur.com/qmNFvXL.png

**Comment by C0rn3j** [comment]
Looks awesome in my opinion. Perhaps add a "next mob" button next to it so we can just cycle through them too to mass report.

**Comment by bschoenmaeckers** [comment]
> Added to a local black list and asked if you'd like to upload the mob ID to a database along with a reason why it should be blocked, so it can be blocked by default in a future mod version. Sounds great.

I don't have a database to send the list to, so I need to look around for a alternative for that.

**Comment by bschoenmaeckers** [comment]
> http://i.imgur.com/zUNIfqO.png
> Yeah a black list with some predefined mod mobs would do wonders..

Which mod adds this mob? I want to test if the blacklist button is rendered above to mob, so you could see it if you want to blacklist a huge mod like that.

**Comment by C0rn3j** [comment]
JurassiCraft-2.0.2.jar

Possibly this one.

**Comment by bschoenmaeckers** [comment]
Finished it. Download version 1.10+ to get it. thank you for helping.

**Comment by C0rn3j** [comment]
Awesome work!

Few questions/suggestions though!

1) Is the blacklist that the user creates sent to you? I'm assuming no

> I don't have a database to send the list too, so I need to look around for a alternative for that.

I could temporarily host a DB for you if you'd like. 

2) If you do implement that, let the user state a reason why are they blocking the mob along with some predefined options (i.e. mob doesn't render, mob is not a mob, mob is so huge it's covering the buttons)

3) I've noticed an option "Only show player models". Personally I'd like the exact opposite of that, where it shows mobs only.

**Comment by bschoenmaeckers** [comment]
Thanks for you feedback!

> I could temporarily host a DB for you if you'd like.
> 
> 2) If you do implement that, let the user state a reason why are they blocking the mob along with some predefined options (i.e. mob doesn't render, mob is not a mob, mob is so huge it's covering the buttons)

That would be great! I'm going to make a nice implementation and add your server to it when its done.

> 3) I've noticed an option "Only show player models". Personally I'd like the exact opposite of that, where it shows mobs only.

I use players as a fallback when it takes too long to find a suiteble mob. Perhaps I move the mob selection process to an other thread so Minecraft doesn't freeze when it takes some time to find a mob. When that's done I can remove the player fallback.
